/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deliveries (tenant-scoped) */
        get: operations["listDeliveries"];
        put?: never;
        /**
         * Create a delivery request
         * @description Ingests a delivery (ADR-001 §4 step 1). Idempotent via `Idempotency-Key`. Returns 202 with the created delivery in `pending`; matching happens asynchronously and progress is delivered via webhooks.
         */
        post: operations["createDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a delivery by id */
        get: operations["getDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a delivery
         * @description Allowed while `pending`/`assigned`; rejected once `picked_up`.
         */
        post: operations["cancelDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook endpoints (no secrets) */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /**
         * Register a webhook endpoint
         * @description Register a URL to receive delivery.* events. The signing `secret` is returned ONCE — store it; every event carries an `X-Delivery-Signature: sha256=<hmac-hex>` header over the raw JSON body.
         */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook-endpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook endpoint */
        delete: operations["deleteWebhookEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a login OTP (SMS)
         * @description Sends a 6-digit code to the phone via SMS. Unauthenticated (the driver has no token yet). Always 202 with a uniform body — never reveals whether the phone is known or in cooldown. Rate-limited per phone.
         */
        post: operations["driverRequestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP → driver bearer token
         * @description Verifies the code and returns a driver bearer token (creating the driver on first login). The token then authenticates every other `/v1/driver/*` call.
         */
        post: operations["driverVerifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Go online (available for offers)
         * @description Marks the authenticated driver available; optionally sets current location so they're immediately eligible for nearby offers. Supply both lat and lng, or neither.
         */
        post: operations["driverGoOnline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Go offline */
        post: operations["driverGoOffline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push a live location ping */
        post: operations["driverUpdateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the driver's live job offers
         * @description Offered, unexpired jobs whose delivery is still pending, soonest-expiring first. Each item is a Delivery plus `offer_expires_at`.
         */
        get: operations["driverListOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The driver's own profile
         * @description Identity + capabilities + active vehicle + derived stats in one lean payload (ADR-003 P0). Heavy sub-resources (vehicle CRUD, documents, payout methods) are their own endpoints.
         */
        get: operations["driverGetProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update driver-editable profile fields
         * @description Name, preferred display name, language preference, and emergency contact. Phone is the OTP identity; approval/status are ops/system-owned; the vehicle is structured (PUT /driver/vehicles). Empty strings clear a field.
         */
        patch: operations["driverUpdateProfile"];
        trace?: never;
    };
    "/driver/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's active vehicle */
        get: operations["driverGetVehicle"];
        /**
         * Set the driver's active vehicle (upsert)
         * @description One active vehicle per driver; re-PUT updates it in place.
         */
        put: operations["driverPutVehicle"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's weekly availability windows */
        get: operations["driverGetSchedule"];
        /**
         * Replace the driver's availability schedule
         * @description Planned weekly hours (ADR-003 P4) — informational, not a hard go-online lock.
         */
        put: operations["driverSetSchedule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-requirement verification status */
        get: operations["driverListDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/documents/{type}/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin a document submission (presigned upload)
         * @description Returns a short-lived presigned PUT URL; the client uploads the file bytes to object storage directly, then calls /driver/documents/confirm. 503 if storage is not configured.
         */
        post: operations["driverDocumentUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/documents/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a document upload completed */
        post: operations["driverConfirmDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/documents/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the current terms (attestation) */
        post: operations["driverAcceptTerms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/payout-methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's payout methods */
        get: operations["driverListPayoutMethods"];
        put?: never;
        /**
         * Add a payout method
         * @description The account reference is encrypted server-side; 503 if payouts are not configured.
         */
        post: operations["driverAddPayoutMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/payout-methods/{id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a payout method the default */
        post: operations["driverSetDefaultPayoutMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate the driver of a completed delivery (tenant → driver)
         * @description 1–5 stars + optional comment, for the tenant's own delivered job. Feeds driver reputation. One per delivery; re-rating overwrites (ADR-003 P3).
         */
        post: operations["rateDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The driver's job history
         * @description Newest first — the Jobs tab. Public delivery shape plus `driver_fee_minor` and per-job facts (`pod_method`, `delivered_at`, `cod_collected_minor`); contacts are deliberately absent (stale customer PII on past jobs). Money aggregates (payable, COD owed) live in /driver/earnings. Cursor-paginated: pass the previous page's `next_before` back as `before` to load older jobs.
         */
        get: operations["driverListDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/offers/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline an offer
         * @description Marks this driver's live offer declined — it is never re-offered to them. Idempotent; declining a lapsed/claimed offer is a harmless no-op.
         */
        post: operations["driverDeclineOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The driver's earnings summary
         * @description All-time accrued payable balance (credits − debits on the driver_payable ledger account) plus today's earnings, where "today" is the Africa/Harare local day. Amounts are minor units.
         */
        get: operations["driverEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/push-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register this device's push token
         * @description Upserts an Expo push token for the authenticated driver, keyed on the token — on a shared phone the device follows whoever logged in last. Push is advisory (offer/cancel wake-ups); the offers list remains the source of truth.
         */
        post: operations["driverRegisterPushToken"];
        /** Remove this device's push token (logout hygiene) */
        delete: operations["driverRemovePushToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the driver's assigned job */
        get: operations["driverGetDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rate a completed delivery (driver → tenant)
         * @description 1–5 stars + optional comment, for a delivered job. One per delivery; re-rating overwrites (ADR-003 P3).
         */
        post: operations["driverRateDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim an offered job
         * @description Atomic — exactly one driver wins a contested offer; losers get 409.
         */
        post: operations["driverClaimDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/picked_up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the job picked up */
        post: operations["driverMarkPickedUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/in_transit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the job in transit */
        post: operations["driverMarkInTransit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/delivered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark the job delivered (+ proof of delivery)
         * @description Completes the delivery: records proof-of-delivery, accrues the driver earning, meters the billable `delivery.completed`, and frees the driver.
         */
        post: operations["driverMarkDelivered"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the job failed */
        post: operations["driverMarkFailed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/pod-photo-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a presigned URL to upload a proof-of-delivery photo
         * @description Mint a short-lived presigned PUT URL so the assigned courier uploads a proof-of-delivery photo directly to private object storage. The driver then completes the job with `method: photo`. Only the assigned courier, only while the job is active. 503 when photo storage is not configured.
         */
        post: operations["driverPodPhotoUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    deliveryEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delivery lifecycle event */
        post: operations["onDeliveryEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        WebhookEndpoint: {
            /** Format: uuid */
            id?: string;
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        WebhookEndpointWithSecret: components["schemas"]["WebhookEndpoint"] & {
            /** @description Shown once at creation. Verify the X-Delivery-Signature with it. */
            secret?: string;
        };
        GeoLocation: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /**
             * @description How the pin was captured. `text_only` = no reliable pin (degraded).
             * @enum {string}
             */
            source: "whatsapp_share" | "map_pin" | "text_only";
            /** @description Human directions — "blue gate opposite the borehole". Critical in informal areas. */
            landmark?: string;
            /** @description Optional free-text address (legacy / fallback). */
            address_text?: string;
            /**
             * Format: date-time
             * @description When the pin was captured (staleness matters for moving customers).
             */
            shared_at?: string;
        };
        Contact: {
            name: string;
            /** @description E.164 (e.g. +263...). Used for driver↔customer coordination. */
            phone: string;
        };
        Package: {
            description?: string;
            /**
             * @default small
             * @enum {string}
             */
            size: "envelope" | "small" | "medium" | "large";
            /** @description Declared value in minor currency units (cents). Optional. */
            value_minor?: number;
        };
        DeliveryRequest: {
            /** @description The tenant's own order id (e.g. urafro order code) for correlation. */
            external_ref?: string;
            pickup: components["schemas"]["GeoLocation"];
            pickup_contact: components["schemas"]["Contact"];
            dropoff: components["schemas"]["GeoLocation"];
            dropoff_contact: components["schemas"]["Contact"];
            package?: components["schemas"]["Package"];
            notes?: string;
            /** @description Cash-on-delivery amount in minor units (cents) the driver collects from the recipient on the merchant's behalf. Distinct from the platform delivery fee (`fee_minor`). Omit for prepaid orders. */
            collect_minor?: number;
        };
        /** @enum {string} */
        DeliveryStatus: "pending" | "assigned" | "picked_up" | "in_transit" | "delivered" | "failed" | "unassigned" | "cancelled";
        Driver: {
            /** Format: uuid */
            id?: string;
            name?: string;
            phone?: string;
            /** Format: uuid */
            courier_org_id?: string | null;
        };
        Delivery: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            external_ref?: string;
            status?: components["schemas"]["DeliveryStatus"];
            pickup?: components["schemas"]["GeoLocation"];
            dropoff?: components["schemas"]["GeoLocation"];
            /** @description Straight-line pickup→dropoff distance in km (1 dp) — the SAME haversine the fee uses, not road distance. Driver UIs present it as approximate ("~7.8 km"). Null if either coordinate is missing. */
            trip_km?: number | null;
            driver?: components["schemas"]["Driver"] | null;
            /** @description Platform delivery fee in minor units, quoted at creation from the pickup→dropoff distance (base + per-km, clamped). The driver earns a configured share of this on completion; the platform keeps the rest. */
            fee_minor?: number | null;
            /** @description Cash-on-delivery amount (minor units); null = prepaid / nothing to collect. */
            collect_minor?: number | null;
            /** @description Why the driver marked it failed; null unless status is `failed`. */
            failure_reason?: components["schemas"]["FailureReason"] | null;
            /** @description At-door proof-of-delivery PIN, generated at intake. **Tenant surfaces only** (create response, GET, list) — relay it to the recipient; it is never present in driver payloads or webhook bodies. The driver submits it on delivered for a verified (`otp`) handover. */
            pod_pin?: string | null;
            /** @description Short-lived signed URL to view the proof-of-delivery photo (present when completed with `method: photo`). **Tenant surfaces only**; null otherwise. */
            pod_photo_url?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /** @enum {string} */
        FailureReason: "customer_unreachable" | "wrong_address" | "customer_refused" | "cash_refused" | "vehicle_problem" | "other";
        DriverState: {
            /** Format: uuid */
            driver_id?: string;
            /** @enum {string} */
            status?: "available" | "offline" | "busy";
        };
        /** @description Computed gates the app renders affordances off — never a single flag. P0 derives can_go_online from approval; later phases add payouts/COD. */
        DriverCapabilities: {
            can_go_online: boolean;
            can_receive_payouts: boolean;
            can_handle_high_value_cod: boolean;
        };
        /** @description The driver's structured active vehicle (ADR-003 P0). */
        DriverVehicle: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "bicycle" | "motorbike" | "car" | "van" | "foot";
            make?: string | null;
            model?: string | null;
            colour?: string | null;
            plate?: string | null;
            year?: number | null;
            capacity_kg?: number | null;
        };
        /** @description Derived reputation/performance (ADR-003 P0). Rates are null until there is a denominator (so UIs show "New", not a fake 0%). Ratings populate in P3. */
        DriverStats: {
            lifetime_jobs: number;
            completed_jobs: number;
            failed_jobs: number;
            offered_count: number;
            accepted_count: number;
            rating_count: number;
            completion_rate: number | null;
            acceptance_rate: number | null;
            rating_avg: number | null;
        };
        /** @description The driver's own composed profile (ADR-003 P0/P1). */
        DriverProfile: {
            /** Format: uuid */
            driver_id: string;
            name: string;
            display_name?: string | null;
            phone: string;
            /**
             * @description The verification state machine (ADR-003 P1); only `verified` can go on shift.
             * @enum {string}
             */
            verification_status: "unverified" | "in_review" | "verified" | "suspended" | "banned";
            /** @description 0 none · 1 identity verified · 2 identity + licence (gates payouts/high-value COD). */
            kyc_tier: number;
            /** @description The driver's collateral-backed COD cash limit (minor units) = min(⅓·vehicle estimated value, KYC-tier ceiling, ops override). 0 until ops value a vehicle — an unvalued driver can't carry COD (ADR-002 §10 / C1). */
            cod_cap_minor: number;
            /** @description COD cash the driver currently holds and owes onward (minor units) (C2). */
            cod_outstanding_minor: number;
            /** @description Remaining COD the driver can still accept = max(0, cap − outstanding) (C8). */
            cod_headroom_minor: number;
            /** @enum {string} */
            status: "available" | "offline" | "busy";
            /** @enum {string} */
            preferred_language: "en" | "sn" | "nd";
            emergency_contact?: {
                name?: string | null;
                phone?: string | null;
            } | null;
            /** Format: date-time */
            member_since: string;
            /** @description The driver's service zone (ADR-003 P4), or null for the open pool. */
            zone?: {
                /** Format: uuid */
                id: string;
                name: string;
            } | null;
            capabilities: components["schemas"]["DriverCapabilities"];
            vehicle?: components["schemas"]["DriverVehicle"] | null;
            vehicle_label?: string | null;
            stats: components["schemas"]["DriverStats"];
        };
        /** @description Per-requirement verification status for the driver's own view (ADR-003 P1; no file URLs — KYC PII stays ops-only). */
        DriverRequirement: {
            /** @enum {string} */
            type: "identity_id" | "profile_photo" | "drivers_licence" | "vehicle_registration" | "terms";
            /** @enum {string} */
            status: "not_submitted" | "pending_review" | "approved" | "rejected" | "expired";
            /** Format: date-time */
            uploaded_at?: string | null;
            review_reason?: string | null;
        };
        /** @description A short-lived URL to PUT a document's bytes directly to object storage (ADR-003 P1). */
        PresignedUpload: {
            /** Format: uuid */
            document_id: string;
            storage_key: string;
            upload: {
                url: string;
                /** @enum {string} */
                method: "PUT";
                expires_in: number;
            };
        };
        /** @description A weekly availability window in local minutes-of-day (ADR-003 P4). */
        ScheduleWindow: {
            /** @description 0=Sun … 6=Sat */
            day_of_week: number;
            start_minute: number;
            end_minute: number;
        };
        /** @description A driver payout method (ADR-003 P2). The full account reference is encrypted server-side — only a masked tail is ever returned. */
        PayoutMethod: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "ecocash" | "bank";
            /** @example •••• 1219 */
            account_ref_mask: string;
            holder_name: string;
            bank_name?: string | null;
            is_default: boolean;
            /** Format: date-time */
            verified_at?: string | null;
        };
        Offer: components["schemas"]["Delivery"] & {
            /**
             * Format: date-time
             * @description When this offer lapses; claim before then or it's withdrawn.
             */
            offer_expires_at?: string;
            /** @description The DRIVER'S share of the fee in minor units — what driver-facing UIs must quote (never the full fee_minor). */
            driver_fee_minor?: number | null;
            /** @description Straight-line distance in km (1 dp) from the driver's last known location to the pickup — how far they'd travel to start the run (ADR-002 Phase B "distance-to-pickup"). Straight-line, not road distance. Null if the driver's position is unknown. */
            pickup_distance_km?: number | null;
        };
        /** @description A delivery as seen by its **assigned driver** — the public Delivery plus the contacts needed to coordinate the run and the driver's own cut of the fee. Returned only on the driver's own endpoints after claiming; contacts never appear in tenant, offer, or webhook payloads. */
        DriverDelivery: components["schemas"]["Delivery"] & {
            pickup_contact?: components["schemas"]["Contact"];
            dropoff_contact?: components["schemas"]["Contact"];
            /** @description The DRIVER'S share of the fee in minor units — what driver-facing UIs must quote (never the full fee_minor). */
            driver_fee_minor?: number | null;
        };
        ProofOfDelivery: {
            /**
             * @description How delivery was proven. Capture UX (photo / at-door OTP) is a later phase.
             * @default manual
             * @enum {string}
             */
            method: "photo" | "signature" | "otp" | "manual";
            note?: string;
            /** @description What the driver actually collected on a COD job (minor units). Omit to book the delivery's full collect_minor; explicit 0 books nothing — the COD ledger records reality and reconciliation surfaces shortfalls. */
            cod_collected_minor?: number;
            /** @description The at-door PIN read out by the recipient. Optional — manual remains the fallback. A match upgrades the PoD method to `otp`; a mismatch rejects the completion (400), capped at 5 attempts per delivery. */
            pod_pin?: string;
        };
        WebhookEvent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "delivery.created" | "delivery.assigned" | "delivery.picked_up" | "delivery.in_transit" | "delivery.completed" | "delivery.failed" | "delivery.unassigned" | "delivery.cancelled";
            /** Format: date-time */
            created_at: string;
            data: {
                delivery?: components["schemas"]["Delivery"];
            };
        };
        Error: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing/invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found (or not visible to this tenant). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but not allowed (e.g. not the assigned driver). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description State conflict (e.g. cancelling an already-picked-up delivery). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Valid shape but unusable (e.g. dropoff has source=text_only and no usable pin). */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Replaying the same key returns the original delivery instead of creating a duplicate. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDeliveries: {
        parameters: {
            query?: {
                status?: components["schemas"]["DeliveryStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of deliveries belonging to the calling tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Delivery"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDelivery: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replaying the same key returns the original delivery instead of creating a duplicate. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryRequest"];
            };
        };
        responses: {
            /** @description Accepted — delivery created in `pending`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The delivery. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This tenant's endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["WebhookEndpoint"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description Created — `secret` is shown only here. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointWithSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverRequestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164, e.g. +263771234567 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description If eligible, an OTP was sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example otp_sent */
                        status?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    driverVerifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164. */
                    phone: string;
                    /** @description The 6-digit code. */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Verified — bearer token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Driver bearer token — store securely; shown once. */
                        token?: string;
                        /** Format: uuid */
                        driver_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGoOnline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: double */
                    lat?: number;
                    /** Format: double */
                    lng?: number;
                };
            };
        };
        responses: {
            /** @description Now available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGoOffline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now offline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverState"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverUpdateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: double */
                    lat: number;
                    /** Format: double */
                    lng: number;
                };
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverListOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The driver's claimable offers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Offer"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGetProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverUpdateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    display_name?: string;
                    /** @enum {string} */
                    preferred_language?: "en" | "sn" | "nd";
                    emergency_contact_name?: string;
                    emergency_contact_phone?: string;
                };
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGetVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active vehicle (or null). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DriverVehicle"] | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverPutVehicle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "bicycle" | "motorbike" | "car" | "van" | "foot";
                    make?: string;
                    model?: string;
                    colour?: string;
                    plate?: string;
                    year?: number;
                    capacity_kg?: number;
                };
            };
        };
        responses: {
            /** @description The saved active vehicle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverVehicle"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGetSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Availability windows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ScheduleWindow"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverSetSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    windows: components["schemas"]["ScheduleWindow"][];
                };
            };
        };
        responses: {
            /** @description Saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverListDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per requirement type. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DriverRequirement"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverDocumentUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "identity_id" | "profile_photo" | "drivers_licence" | "vehicle_registration";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned upload. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUpload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Document storage is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    driverConfirmDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    document_id: string;
                };
            };
        };
        responses: {
            /** @description Confirmed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverAcceptTerms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    version: string;
                };
            };
        };
        responses: {
            /** @description Accepted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverListPayoutMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payout methods (masked). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PayoutMethod"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverAddPayoutMethod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "ecocash" | "bank";
                    account_ref: string;
                    holder_name: string;
                    bank_name?: string;
                };
            };
        };
        responses: {
            /** @description The saved method (masked). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutMethod"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Payouts are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    driverSetDefaultPayoutMethod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    rateDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    stars: number;
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description Rated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverListDeliveries: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque pagination cursor — pass the previous page's `next_before` verbatim to load older jobs. (Internally `<updated_at>|<id>`; treat as opaque.) A malformed cursor returns the first page. */
                before?: string;
                /** @description Filter to a single delivery status (e.g. delivered, failed). */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job history page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["Delivery"] & {
                            driver_fee_minor?: number | null;
                            /**
                             * @description How the handover was confirmed (delivered jobs).
                             * @enum {string|null}
                             */
                            pod_method?: "photo" | "signature" | "otp" | "manual" | null;
                            /**
                             * Format: date-time
                             * @description Completion time (PoD geostamp); null unless delivered.
                             */
                            delivered_at?: string | null;
                            /** @description Cash actually collected on this run (vs collect_minor due). */
                            cod_collected_minor?: number | null;
                        })[];
                        /** @description Opaque cursor for the next (older) page — pass it back as `before`. Null when there are no more jobs. */
                        next_before: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverDeclineOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Declined (or already moot). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverEarnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Earnings summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        payable_minor: number;
                        today_minor: number;
                        today_deliveries: number;
                        /** @description COD cash float currently in the driver's hands, owed onward. */
                        cod_owed_minor: number;
                        /** @example USD */
                        currency: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverRegisterPushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** @enum {string} */
                    platform: "android" | "ios";
                };
            };
        };
        responses: {
            /** @description Registered. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverRemovePushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Removed (idempotent). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGetDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The delivery — only if assigned to this driver. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverRateDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    stars: number;
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description Rated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverClaimDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claimed — now `assigned` to this driver. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkPickedUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now `picked_up`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkInTransit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now `in_transit`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkDelivered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProofOfDelivery"];
            };
        };
        responses: {
            /** @description Now `delivered`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkFailed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: components["schemas"]["FailureReason"];
                };
            };
        };
        responses: {
            /** @description Now `failed`; the driver is freed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverPodPhotoUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Presigned upload for the PoD photo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        storage_key: string;
                        upload: {
                            url: string;
                            /** @enum {string} */
                            method: "PUT";
                            expires_in: number;
                        };
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description Photo storage is not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    onDeliveryEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookEvent"];
            };
        };
        responses: {
            /** @description Acknowledged. Non-2xx (or timeout) triggers signed retries with backoff. */
            "2XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
