/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List deliveries (tenant-scoped) */
        get: operations["listDeliveries"];
        put?: never;
        /**
         * Create a delivery request
         * @description Ingests a delivery (ADR-001 §4 step 1). Idempotent via `Idempotency-Key`. Returns 202 with the created delivery in `pending`; matching happens asynchronously and progress is delivered via webhooks.
         */
        post: operations["createDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a delivery by id */
        get: operations["getDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a delivery
         * @description Allowed while `pending`/`assigned`; rejected once `picked_up`.
         */
        post: operations["cancelDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook endpoints (no secrets) */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /**
         * Register a webhook endpoint
         * @description Register a URL to receive delivery.* events. The signing `secret` is returned ONCE — store it; every event carries an `X-Delivery-Signature: sha256=<hmac-hex>` header over the raw JSON body.
         */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook-endpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a webhook endpoint */
        delete: operations["deleteWebhookEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/auth/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a login OTP (SMS)
         * @description Sends a 6-digit code to the phone via SMS. Unauthenticated (the driver has no token yet). Always 202 with a uniform body — never reveals whether the phone is known or in cooldown. Rate-limited per phone.
         */
        post: operations["driverRequestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP → driver bearer token
         * @description Verifies the code and returns a driver bearer token (creating the driver on first login). The token then authenticates every other `/v1/driver/*` call.
         */
        post: operations["driverVerifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/online": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Go online (available for offers)
         * @description Marks the authenticated driver available; optionally sets current location so they're immediately eligible for nearby offers. Supply both lat and lng, or neither.
         */
        post: operations["driverGoOnline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Go offline */
        post: operations["driverGoOffline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push a live location ping */
        post: operations["driverUpdateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the driver's live job offers
         * @description Offered, unexpired jobs whose delivery is still pending, soonest-expiring first. Each item is a Delivery plus `offer_expires_at`.
         */
        get: operations["driverListOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the driver's assigned job */
        get: operations["driverGetDelivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim an offered job
         * @description Atomic — exactly one driver wins a contested offer; losers get 409.
         */
        post: operations["driverClaimDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/picked_up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the job picked up */
        post: operations["driverMarkPickedUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/in_transit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the job in transit */
        post: operations["driverMarkInTransit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/delivered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark the job delivered (+ proof of delivery)
         * @description Completes the delivery: records proof-of-delivery, accrues the driver earning, meters the billable `delivery.completed`, and frees the driver.
         */
        post: operations["driverMarkDelivered"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/driver/deliveries/{id}/failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the job failed */
        post: operations["driverMarkFailed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    deliveryEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delivery lifecycle event */
        post: operations["onDeliveryEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        WebhookEndpoint: {
            /** Format: uuid */
            id?: string;
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        WebhookEndpointWithSecret: components["schemas"]["WebhookEndpoint"] & {
            /** @description Shown once at creation. Verify the X-Delivery-Signature with it. */
            secret?: string;
        };
        GeoLocation: {
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /**
             * @description How the pin was captured. `text_only` = no reliable pin (degraded).
             * @enum {string}
             */
            source: "whatsapp_share" | "map_pin" | "text_only";
            /** @description Human directions — "blue gate opposite the borehole". Critical in informal areas. */
            landmark?: string;
            /** @description Optional free-text address (legacy / fallback). */
            address_text?: string;
            /**
             * Format: date-time
             * @description When the pin was captured (staleness matters for moving customers).
             */
            shared_at?: string;
        };
        Contact: {
            name: string;
            /** @description E.164 (e.g. +263...). Used for driver↔customer coordination. */
            phone: string;
        };
        Package: {
            description?: string;
            /**
             * @default small
             * @enum {string}
             */
            size: "envelope" | "small" | "medium" | "large";
            /** @description Declared value in minor currency units (cents). Optional. */
            value_minor?: number;
        };
        DeliveryRequest: {
            /** @description The tenant's own order id (e.g. urafro order code) for correlation. */
            external_ref?: string;
            pickup: components["schemas"]["GeoLocation"];
            pickup_contact: components["schemas"]["Contact"];
            dropoff: components["schemas"]["GeoLocation"];
            dropoff_contact: components["schemas"]["Contact"];
            package?: components["schemas"]["Package"];
            notes?: string;
            /** @description Cash-on-delivery amount in minor units (cents) the driver collects from the recipient on the merchant's behalf. Distinct from the platform delivery fee (`fee_minor`). Omit for prepaid orders. */
            collect_minor?: number;
        };
        /** @enum {string} */
        DeliveryStatus: "pending" | "assigned" | "picked_up" | "in_transit" | "delivered" | "failed" | "unassigned" | "cancelled";
        Driver: {
            /** Format: uuid */
            id?: string;
            name?: string;
            phone?: string;
            /** Format: uuid */
            courier_org_id?: string | null;
        };
        Delivery: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            external_ref?: string;
            status?: components["schemas"]["DeliveryStatus"];
            pickup?: components["schemas"]["GeoLocation"];
            dropoff?: components["schemas"]["GeoLocation"];
            driver?: components["schemas"]["Driver"] | null;
            /** @description Platform delivery fee in minor units, quoted at creation from the pickup→dropoff distance (base + per-km, clamped). The driver earns a configured share of this on completion; the platform keeps the rest. */
            fee_minor?: number | null;
            /** @description Cash-on-delivery amount (minor units); null = prepaid / nothing to collect. */
            collect_minor?: number | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        DriverState: {
            /** Format: uuid */
            driver_id?: string;
            /** @enum {string} */
            status?: "available" | "offline" | "busy";
        };
        Offer: components["schemas"]["Delivery"] & {
            /**
             * Format: date-time
             * @description When this offer lapses; claim before then or it's withdrawn.
             */
            offer_expires_at?: string;
        };
        /** @description A delivery as seen by its **assigned driver** — the public Delivery plus the contacts needed to coordinate the run. Returned only on the driver's own endpoints after claiming; contacts never appear in tenant, offer, or webhook payloads. */
        DriverDelivery: components["schemas"]["Delivery"] & {
            pickup_contact?: components["schemas"]["Contact"];
            dropoff_contact?: components["schemas"]["Contact"];
        };
        ProofOfDelivery: {
            /**
             * @description How delivery was proven. Capture UX (photo / at-door OTP) is a later phase.
             * @default manual
             * @enum {string}
             */
            method: "photo" | "signature" | "otp" | "manual";
            note?: string;
        };
        WebhookEvent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "delivery.created" | "delivery.assigned" | "delivery.picked_up" | "delivery.in_transit" | "delivery.completed" | "delivery.failed" | "delivery.unassigned" | "delivery.cancelled";
            /** Format: date-time */
            created_at: string;
            data: {
                delivery?: components["schemas"]["Delivery"];
            };
        };
        Error: {
            error: {
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing/invalid API key. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found (or not visible to this tenant). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated, but not allowed (e.g. not the assigned driver). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description State conflict (e.g. cancelling an already-picked-up delivery). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Valid shape but unusable (e.g. dropoff has source=text_only and no usable pin). */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Replaying the same key returns the original delivery instead of creating a duplicate. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDeliveries: {
        parameters: {
            query?: {
                status?: components["schemas"]["DeliveryStatus"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of deliveries belonging to the calling tenant. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Delivery"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createDelivery: {
        parameters: {
            query?: never;
            header?: {
                /** @description Replaying the same key returns the original delivery instead of creating a duplicate. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryRequest"];
            };
        };
        responses: {
            /** @description Accepted — delivery created in `pending`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The delivery. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This tenant's endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["WebhookEndpoint"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                };
            };
        };
        responses: {
            /** @description Created — `secret` is shown only here. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointWithSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverRequestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164, e.g. +263771234567 */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description If eligible, an OTP was sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example otp_sent */
                        status?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    driverVerifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164. */
                    phone: string;
                    /** @description The 6-digit code. */
                    code: string;
                };
            };
        };
        responses: {
            /** @description Verified — bearer token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Driver bearer token — store securely; shown once. */
                        token?: string;
                        /** Format: uuid */
                        driver_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGoOnline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: double */
                    lat?: number;
                    /** Format: double */
                    lng?: number;
                };
            };
        };
        responses: {
            /** @description Now available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverState"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGoOffline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now offline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverState"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverUpdateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: double */
                    lat: number;
                    /** Format: double */
                    lng: number;
                };
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverListOffers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The driver's claimable offers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Offer"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    driverGetDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The delivery — only if assigned to this driver. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    driverClaimDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claimed — now `assigned` to this driver. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkPickedUp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now `picked_up`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkInTransit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now `in_transit`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkDelivered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProofOfDelivery"];
            };
        };
        responses: {
            /** @description Now `delivered`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    driverMarkFailed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now `failed`; the driver is freed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverDelivery"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    onDeliveryEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookEvent"];
            };
        };
        responses: {
            /** @description Acknowledged. Non-2xx (or timeout) triggers signed retries with backoff. */
            "2XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
