// GENERATED by scripts/gen-contract-stamp.mjs — DO NOT EDIT.
//
// Identity of the vendored urafro-next /v1 contract this client was built from.
// Regenerated by the same npm script that regenerates the API types, so the
// existing CI drift gate (regen + `git diff --exit-code`) also covers it.
//
// If this file changes, the contract changed. If it did NOT change after a
// re-vendor, the vendored copy is byte-identical to what it was before.
export const CONTRACT_VERSION = '1.12.0';
export const CONTRACT_SHA256 = 'b1a677ca444383588f10c698d7f5bb4ab93af24a69be3b44bca1a904d240bbf5';
