// GENERATED by scripts/gen-contract-stamp.mjs — DO NOT EDIT.
//
// Identity of the vendored urafro-next /v1 contract this client was built from.
// Regenerated by the same npm script that regenerates the API types, so the
// existing CI drift gate (regen + `git diff --exit-code`) also covers it.
//
// If this file changes, the contract changed. If it did NOT change after a
// re-vendor, the vendored copy is byte-identical to what it was before.
export const CONTRACT_VERSION = '1.13.0';
export const CONTRACT_SHA256 = '23f623cc84d815b0767166390974aa866d58df37ebea079ef1363debba0e1c61';
