// GENERATED by scripts/gen-contract-stamp.mjs — DO NOT EDIT.
//
// Identity of the vendored urafro-next /v1 contract this client was built from.
// Regenerated by the same npm script that regenerates the API types, so the
// existing CI drift gate (regen + `git diff --exit-code`) also covers it.
//
// If this file changes, the contract changed. If it did NOT change after a
// re-vendor, the vendored copy is byte-identical to what it was before.
export const CONTRACT_VERSION = '1.11.0';
export const CONTRACT_SHA256 = '5eb904a7bbfcc4b9cf8801476075c3b679acd4cc521fe209d51b2b425b68c285';
